
server:
  port: 8081
angryfrog:
 :angryfrog:

main:
  liquibase:
    change-log: classpath:sql/change_log.sql

spring:
  profiles:
    active: ${ENV_NAME:}

  datasource:
    url: jdbc:mysql://localtest:3306/frogbot?serverTimezone=UTC
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

wish:
  guarantee:
    character:
      purple: 10
      golden: 90
